# Generated by Django 2.1.5 on 2019-03-30 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190329_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='t_file',
            field=models.FileField(blank=True, null=True, upload_to='file/%Y%m'),
        ),
    ]
