# Generated by Django 2.1.5 on 2019-03-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Start',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_choices', models.CharField(choices=[('ys', '阳山'), ('qy', '清远'), ('gz', '广州')], default='ys', max_length=20, verbose_name='出发')),
                ('end_choices', models.CharField(choices=[('ys', '阳山'), ('qy', '清远'), ('gz', '广州')], default='ys', max_length=20, verbose_name='到达')),
                ('name', models.CharField(max_length=20, verbose_name='昵称')),
                ('start_time', models.DateTimeField(verbose_name='出发时间')),
                ('start_img', models.ImageField(blank=True, default='images/1.gif', upload_to='images/%m%d', verbose_name='图片')),
            ],
            options={
                'verbose_name': '测试',
                'verbose_name_plural': '测试',
            },
        ),
    ]
